apiVersion: 1
groups:
    - orgId: 1
      name: 1m
      folder: Celery
      interval: 1m
      rules:
        - uid: aedjay5mtqnswb
          title: High rate
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: PBFA97CFB590B2093
              model:
                editorMode: code
                expr: 100 * sum(increase(celery_task_failed_total{name="tasks.tasks.add"}[1m])) by (name) / sum(increase(celery_task_received_total{name="tasks.tasks.add"}[1m])) by (name)
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 20
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: NoData
          execErrState: Error
          for: 1m
          annotations:
            summary: Error
          isPaused: false
          notification_settings:
            receiver: grafana-default-email
