global:
  scrape_interval: 5s
  scrape_timeout: 4s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'celery'
    static_configs:
      - targets: ['celery-exporter:9808']
    metrics_path: '/metrics' 